package com.booknest.activity;

public enum ActivityEventType {
	LOAN_CHECKED_OUT,
	LOAN_RETURNED,
	LOAN_RENEWED,
	RESERVATION_PLACED,
	RESERVATION_HELD,
	RESERVATION_CANCELLED,
	RESERVATION_FULFILLED
}
