CREATE TABLE staff_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    CONSTRAINT uk_staff_accounts_username UNIQUE (username)
);
