CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    isbn VARCHAR(13),
    genre VARCHAR(100),
    publication_year INTEGER,
    description VARCHAR(2000),
    CONSTRAINT uk_books_isbn UNIQUE (isbn),
    CONSTRAINT ck_books_publication_year
        CHECK (publication_year IS NULL OR publication_year BETWEEN 1000 AND 2100)
);

CREATE TABLE book_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_book_copies_book
        FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE RESTRICT,
    CONSTRAINT ck_book_copies_status
        CHECK (status IN ('AVAILABLE', 'MAINTENANCE', 'RETIRED'))
);

CREATE INDEX idx_book_copies_book_id ON book_copies (book_id);
