CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(30),
    notes VARCHAR(1000)
);

CREATE INDEX idx_members_full_name_id ON members (full_name, id);
