ALTER TABLE book_copies
    DROP CONSTRAINT ck_book_copies_status;

ALTER TABLE book_copies
    ADD CONSTRAINT ck_book_copies_status
        CHECK (status IN ('AVAILABLE', 'ON_LOAN', 'MAINTENANCE', 'RETIRED'));

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_copy_id BIGINT NOT NULL,
    active_copy_id BIGINT,
    checkout_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    checkout_staff_id BIGINT NOT NULL,
    return_staff_id BIGINT,
    CONSTRAINT fk_loans_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_loans_book_copy
        FOREIGN KEY (book_copy_id) REFERENCES book_copies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_loans_active_copy
        FOREIGN KEY (active_copy_id) REFERENCES book_copies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_loans_checkout_staff
        FOREIGN KEY (checkout_staff_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_loans_return_staff
        FOREIGN KEY (return_staff_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT uk_loans_active_copy UNIQUE (active_copy_id),
    CONSTRAINT ck_loans_dates CHECK (
        due_date >= checkout_date
        AND (return_date IS NULL OR return_date >= checkout_date)
    ),
    CONSTRAINT ck_loans_active_copy_state CHECK (
        (return_date IS NULL AND return_staff_id IS NULL
            AND active_copy_id IS NOT NULL AND active_copy_id = book_copy_id)
        OR (return_date IS NOT NULL AND return_staff_id IS NOT NULL AND active_copy_id IS NULL)
    )
);

CREATE INDEX idx_loans_member_id ON loans (member_id);
CREATE INDEX idx_loans_book_copy_id ON loans (book_copy_id);
CREATE INDEX idx_loans_return_due_date ON loans (return_date, due_date);
