ALTER TABLE staff_accounts
    ADD COLUMN role VARCHAR(16) NOT NULL DEFAULT 'STAFF';

ALTER TABLE staff_accounts
    ADD COLUMN password_change_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE staff_accounts
    ADD COLUMN credential_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE staff_accounts
    ADD CONSTRAINT ck_staff_accounts_role CHECK (role IN ('ADMIN', 'STAFF', 'PATRON'));

ALTER TABLE members
    ADD COLUMN account_id BIGINT;

ALTER TABLE members
    ADD CONSTRAINT uk_members_account_id UNIQUE (account_id);

ALTER TABLE members
    ADD CONSTRAINT fk_members_account
        FOREIGN KEY (account_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT;

CREATE TABLE system_admin_identity (
    singleton_id SMALLINT PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT ck_system_admin_identity_singleton CHECK (singleton_id = 1),
    CONSTRAINT fk_system_admin_identity_account
        FOREIGN KEY (account_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT
);

CREATE TABLE password_reset_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id BIGINT,
    target_account_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    reset_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_password_reset_event_type
        CHECK (event_type IN ('STAFF_CREATED', 'PASSWORD_RESET', 'ADMIN_RECOVERY')),
    CONSTRAINT fk_password_reset_actor
        FOREIGN KEY (actor_account_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_password_reset_target
        FOREIGN KEY (target_account_id) REFERENCES staff_accounts (id) ON DELETE RESTRICT
);

CREATE INDEX idx_password_reset_events_target_time
    ON password_reset_events (target_account_id, reset_at DESC);
