ALTER TABLE book_copies DROP CONSTRAINT ck_book_copies_status;

ALTER TABLE book_copies
    ADD CONSTRAINT ck_book_copies_status
        CHECK (status IN ('AVAILABLE', 'ON_LOAN', 'ON_HOLD', 'MAINTENANCE', 'RETIRED'));

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    copy_id BIGINT,
    status VARCHAR(16) NOT NULL,
    active_member_book_key VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('WAITING', 'HELD', 'CANCELLED', 'FULFILLED')),
    CONSTRAINT ck_reservations_held_copy CHECK (
        (status = 'HELD' AND copy_id IS NOT NULL)
        OR (status <> 'HELD' AND copy_id IS NULL)
    ),
    CONSTRAINT fk_reservations_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservations_book
        FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservations_copy
        FOREIGN KEY (copy_id) REFERENCES book_copies (id) ON DELETE RESTRICT,
    CONSTRAINT uk_reservations_active_member_book UNIQUE (active_member_book_key)
);

CREATE INDEX idx_reservations_queue ON reservations (book_id, status, id);
CREATE INDEX idx_reservations_member_id ON reservations (member_id, id);
