CREATE TABLE activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_username VARCHAR(50) NOT NULL,
    patron_account_id BIGINT,
    member_id BIGINT,
    member_name VARCHAR(150),
    book_id BIGINT,
    book_title VARCHAR(200),
    copy_id BIGINT,
    loan_id BIGINT,
    reservation_id BIGINT
);

CREATE INDEX ix_activity_events_timeline ON activity_events (occurred_at DESC, id DESC);
CREATE INDEX ix_activity_events_patron_timeline
    ON activity_events (patron_account_id, occurred_at DESC, id DESC);
